### ISSUE TITLE
Status page shows conflicting information when disconnected

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-dashboard#106]
The red cross in the sidebar indicates that the dashboard is disconnected from the server, while the status page itself says that it's connected to the server. 

![disconnected](https://user-images.githubusercontent.com/2684622/93334478-4c8cdd80-f825-11ea-9c3c-eb9c1e8479df.png)

**Comment by wouterdb** [comment]
Change label to 'Api URL'
