### ISSUE TITLE
Verify if the jenkins job has a cleanup post build step

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-dashboard#126]

**Comment by andraskvr** [comment]
It already has a cleanup step, checked on master, iso3, iso4 branches:
https://github.com/inmanta/inmanta-dashboard/blob/805f528403ef54f2eb638b0fdd103de2f0c07e48/Jenkinsfile#L19
And the workspaces are deleted indeed.
Closing the issue.
