### ISSUE TITLE
Allow the application to work behind a proxy

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/inmanta-dashboard#130]
The baseUrl for the API and the UI should be configurable.
This will allow the proxy to work.
You should be able to set the baseUrl up front.
Example: `hostname.com:xxxx/sub1/sub2/`
If the baseUrl does not contain a trailing forward slash, a forward slash will be appended.

1. update config.js to not use location.orgin but take the correct part of the location 
1. test by hand (click through a bit to find broken links)

**Comment by bartv** [comment]
It is possible to autodetect this? So that it goes one level up from where index.html is loaded?

**Comment by Stijnkool** [comment]
Yea, this should be possible before we invoke react and therefor react-router.

**Comment by bartv** [comment]
@Stijnkool I think we can close this now, no?

**Comment by Stijnkool** [comment]
This has been implemented in the **web-console**.
But I'm not sure if any changes have been implemented in the **dashboard**.
And we still need to properly test this with an actual setup.
I will verify this with @andraskvr next week.
