### ISSUE TITLE
An exception occured: ("'str' object has no attribute 'name'",) when opening Versions > Deploy Report

### ISSUE THREAD

**Issue by automate-solutions** [inmanta/inmanta-dashboard#6]
When I try to look at the Deploy Report, I can see this error:
<img width="1038" alt="screen shot 2017-07-03 at 10 08 10" src="https://user-images.githubusercontent.com/28261191/27783719-a933306e-5fd7-11e7-84ba-3f2031ed2850.png">
And, even if I wait for a long time, I never get the report

**Comment by bartv** [comment]
This view does no longer affer anything over the normal version view. It has been removed.
