### ISSUE TITLE
Agent processes are filtered incorrectly

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-dashboard#91]
When the `!` is put as a filter on the expired field, no agent processes are shown when non-expired agent processes exist.

![agent_procs](https://user-images.githubusercontent.com/2684622/86355890-a2f96f80-bc6b-11ea-9511-c4af31fc545a.png)

**Comment by arnaudsjs** [comment]
This issue seems to be back.

**Comment by bartv** [comment]
We are not going to fix this anymore in the dashboard
